// mock-server/db/locations.cjs
const locations = [
  {
    id: '1',
    name: 'Sigiriya Rock Fortress',
    description:
      'Ancient rock fortress and palace ruins, UNESCO World Heritage Site. Features stunning frescoes and landscaped gardens.',
    city: 'Sigiriya',
    province: 'Central Province',
    location_type: 'tourist_spot',
    latitude: 7.957,
    longitude: 80.7603,
    entryFee: 30,
    bestTimeToVisit: 'December to April',
    averageVisitDuration: '3-4 hours',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '2',
    name: 'Temple of the Tooth',
    description:
      'Sacred Buddhist temple housing a tooth relic of Buddha. Located in the royal palace complex of Kandy.',
    city: 'Kandy',
    province: 'Central Province',
    location_type: 'tourist_spot',
    latitude: 7.2935,
    longitude: 80.6405,
    entryFee: 10,
    bestTimeToVisit: 'Year-round',
    averageVisitDuration: '2-3 hours',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '3',
    name: 'Yala National Park',
    description:
      'Premier wildlife sanctuary known for leopards, elephants, and diverse bird species. Safari destination.',
    city: 'Yala',
    province: 'Southern Province',
    location_type: 'tourist_spot',
    latitude: 6.3712,
    longitude: 81.5199,
    entryFee: 25,
    bestTimeToVisit: 'February to July',
    averageVisitDuration: 'Half day',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '4',
    name: 'Galle Fort',
    description:
      'Historic fort built by Portuguese and fortified by Dutch. Picturesque streets, cafes, and colonial architecture.',
    city: 'Galle',
    province: 'Southern Province',
    location_type: 'tourist_spot',
    latitude: 6.0329,
    longitude: 80.2168,
    entryFee: 0,
    bestTimeToVisit: 'December to March',
    averageVisitDuration: '3-5 hours',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '5',
    name: 'Nuwara Eliya Tea Plantations',
    description:
      "Lush tea estates in Sri Lanka's hill country. Cool climate, British colonial architecture, and scenic views.",
    city: 'Nuwara Eliya',
    province: 'Central Province',
    location_type: 'tourist_spot',
    latitude: 6.9497,
    longitude: 80.7891,
    entryFee: 5,
    bestTimeToVisit: 'January to March',
    averageVisitDuration: 'Full day',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '6',
    name: 'Mirissa Beach',
    description:
      'Pristine beach destination perfect for whale watching, surfing, and relaxation. Crystal clear waters.',
    city: 'Mirissa',
    province: 'Southern Province',
    location_type: 'tourist_spot',
    latitude: 5.9467,
    longitude: 80.4681,
    entryFee: 0,
    bestTimeToVisit: 'November to April',
    averageVisitDuration: 'Full day',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '7',
    name: 'Grand Hotel Kandy',
    description:
      'Luxury colonial hotel overlooking Kandy Lake with traditional Sri Lankan architecture.',
    city: 'Kandy',
    province: 'Central Province',
    location_type: 'accommodation',
    latitude: 7.2906,
    longitude: 80.6337,
    entryFee: 0,
    bestTimeToVisit: 'Year-round',
    averageVisitDuration: 'Overnight',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '8',
    name: 'Jetwing Yala',
    description:
      'Luxury safari lodge located within Yala National Park with wildlife viewing opportunities.',
    city: 'Yala',
    province: 'Southern Province',
    location_type: 'accommodation',
    latitude: 6.3712,
    longitude: 81.5199,
    entryFee: 0,
    bestTimeToVisit: 'February to July',
    averageVisitDuration: 'Overnight',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '9',
    name: 'The Fortress Galle',
    description: 'Boutique hotel located within the historic Galle Fort walls.',
    city: 'Galle',
    province: 'Southern Province',
    location_type: 'accommodation',
    latitude: 6.0329,
    longitude: 80.2168,
    entryFee: 0,
    bestTimeToVisit: 'December to March',
    averageVisitDuration: 'Overnight',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '10',
    name: 'Heritage Restaurant Kandy',
    description: 'Traditional Sri Lankan cuisine in a colonial setting overlooking the lake.',
    city: 'Kandy',
    province: 'Central Province',
    location_type: 'restaurant',
    latitude: 7.2906,
    longitude: 80.6337,
    entryFee: 0,
    bestTimeToVisit: 'Year-round',
    averageVisitDuration: '1-2 hours',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
  {
    id: '11',
    name: 'Safari Jeep Tour',
    description: 'Guided wildlife safari through Yala National Park in an open jeep.',
    city: 'Yala',
    province: 'Southern Province',
    location_type: 'activity',
    latitude: 6.3712,
    longitude: 81.5199,
    entryFee: 50,
    bestTimeToVisit: 'February to July',
    averageVisitDuration: '4-6 hours',
    isActive: true,
    createdAt: '2025-01-10T10:00:00.000Z',
    updatedAt: '2025-10-15T14:00:00.000Z',
  },
];

module.exports = { locations };
