// mock-server/db/packages.cjs
const packages = [
  {
    id: '1',
    name: 'Cultural Triangle Explorer',
    description:
      "7-day journey through Sri Lanka's ancient cities including Sigiriya, Polonnaruwa, and Anuradhapura. Explore UNESCO World Heritage Sites.",
    duration: 7,
    price: 850,
    maxPeople: 8,
    difficulty: 'moderate',
    category: 'cultural',
    includes: [
      'Accommodation (4-star hotels)',
      'Daily breakfast and dinner',
      'Air-conditioned vehicle',
      'English-speaking guide',
      'Entrance fees',
    ],
    excludes: ['International flights', 'Lunch', 'Personal expenses', 'Travel insurance'],
    highlights: [
      'Sigiriya Rock Fortress',
      'Dambulla Cave Temple',
      'Ancient city of Polonnaruwa',
      'Sacred city of Anuradhapura',
    ],
    isActive: true,
    createdAt: '2025-01-15T10:00:00.000Z',
    updatedAt: '2025-10-30T08:53:29.398Z',
  },
  {
    id: '2',
    name: 'Beach & Wildlife Adventure',
    description:
      '10-day coastal and wildlife experience. Safari in Yala, relax on pristine beaches, and explore Galle Fort.',
    duration: 10,
    price: 1250,
    maxPeople: 6,
    difficulty: 'easy',
    category: 'adventure',
    includes: [
      'Accommodation (beach resorts & lodges)',
      'All meals',
      'Safari jeep with tracker',
      'Boat trips',
      'Entrance fees',
    ],
    excludes: [
      'International flights',
      'Alcoholic beverages',
      'Personal expenses',
      'Optional activities',
    ],
    highlights: [
      'Yala National Park Safari',
      'Whale watching in Mirissa',
      'Galle Fort walking tour',
      'Beach relaxation',
    ],
    isActive: true,
    createdAt: '2025-01-15T10:00:00.000Z',
    updatedAt: '2025-10-10T14:00:00.000Z',
  },
  {
    id: '3',
    name: 'Hill Country Tea Experience',
    description:
      "5-day exploration of Sri Lanka's picturesque hill country. Visit tea plantations, waterfalls, and charming colonial towns.",
    duration: 5,
    price: 650,
    maxPeople: 10,
    difficulty: 'easy',
    category: 'nature',
    includes: [
      'Boutique hotel accommodation',
      'Daily breakfast',
      'Train tickets (Kandy to Ella)',
      'Tea plantation tour',
      'Guide services',
    ],
    excludes: ['International flights', 'Lunch and dinner', 'Personal expenses', 'Tips'],
    highlights: [
      'Nuwara Eliya tea estates',
      'Scenic train journey',
      'Ramboda Falls',
      'Temple of the Tooth Kandy',
    ],
    isActive: true,
    createdAt: '2025-01-15T10:00:00.000Z',
    updatedAt: '2025-10-10T14:00:00.000Z',
  },
  {
    id: '4',
    name: 'Complete Sri Lanka',
    description:
      '14-day comprehensive tour covering culture, wildlife, beaches, and hill country. The ultimate Sri Lankan experience.',
    duration: 14,
    price: 1850,
    maxPeople: 12,
    difficulty: 'moderate',
    category: 'comprehensive',
    includes: [
      'Deluxe accommodation',
      'All meals',
      'Private vehicle',
      'Experienced guide',
      'All entrance fees',
      'Safari & whale watching',
    ],
    excludes: ['International flights', 'Visa fees', 'Travel insurance', 'Personal expenses'],
    highlights: [
      'Cultural Triangle sites',
      'Yala Safari',
      'Beach relaxation',
      'Hill country & tea',
      'Galle Fort',
      'Kandy Perahera (seasonal)',
    ],
    isActive: true,
    createdAt: '2025-01-15T10:00:00.000Z',
    updatedAt: '2025-10-10T14:00:00.000Z',
  },
  {
    id: '5',
    name: 'Weekend Getaway - Kandy & Nuwara Eliya',
    description:
      "3-day quick escape to Sri Lanka's cultural and scenic hill country. Perfect for short trips.",
    duration: 3,
    price: 380,
    maxPeople: 4,
    difficulty: 'easy',
    category: 'short-trip',
    includes: ['Hotel accommodation', 'Breakfast', 'Private car with driver', 'Temple entry fees'],
    excludes: [
      'International flights',
      'Lunch and dinner',
      'Optional activities',
      'Personal expenses',
    ],
    highlights: [
      'Temple of the Tooth',
      'Kandy Lake',
      'Nuwara Eliya town tour',
      'Tea factory visit',
    ],
    isActive: true,
    createdAt: '2025-01-15T10:00:00.000Z',
    updatedAt: '2025-10-30T09:05:07.527Z',
  },
];

module.exports = { packages };
